don't fail in cleanup

diff --git a/scripts/bootstrap/bootstrap b/scripts/bootstrap/bootstrap
--- a/scripts/bootstrap/bootstrap
+++ b/scripts/bootstrap/bootstrap
@@ -33,10 +33,10 @@ toltec_remote="${toltec_remote:-https://toltec-dev.org/$toltec_branch/rmall}"
 
 # Remove all temporary files
 cleanup() {
-    echo "broken!!! - cleaning up $wget_path and $opkg_path"
-    >>~/cleaned-up date
-    >>~/cleaned-up cat <(caller 0; caller 1; caller 2)
-    rm -f "$wget_path" "$opkg_path"
+    echo "broken!!! - cleaning up $wget_path and $opkg_path" || true
+    >>~/cleaned-up date || true
+    >>~/cleaned-up cat <(caller 0; caller 1; caller 2) || true
+    rm -f "$wget_path" "$opkg_path" || echo "failed to delete files?" || true
 }
 
 # Remove unfinished installation after unexpected error
